const APP_VERSION = "5.2";
let L=1,T=0,realMode=false;
const DICONS=["\uD83D\uDCD6","\uD83D\uDD32","\uD83D\uDD04","\u2699\uFE0F","\uD83D\uDDFA\uFE0F","\uD83E\uDD16","\uD83D\uDD17"];
const DCOLORS=["#58a6ff","#f0883e","#238636","#bc8cff","#f778ba","#79c0ff","#ffa657"];
const DN=[["D1 T\u00e9rminos y Conceptos","D1 Key Terms &amp; Concepts"],["D2 Las 4 Dimensiones","D2 The 4 Dimensions"],["D3 PSLM (Lifecycle)","D3 PSLM (Lifecycle)"],["D4 Sistema de Valor ITIL","D4 ITIL Value System"],["D5 Flujos de Valor","D5 Value Streams"],["D6 ITIL e IA","D6 ITIL &amp; AI"],["D7 ITIL y Otros Marcos","D7 ITIL &amp; Frameworks"]];
const DFULL=[["T\u00e9rminos y Definiciones Clave","Key Terms &amp; Definitions"],["Las Cuatro Dimensiones","The Four Dimensions"],["Ciclo de Vida del Producto y Servicio (PSLM)","Product &amp; Service Lifecycle (PSLM)"],["Sistema de Valor ITIL (SVS)","ITIL Value System (SVS)"],["Identificaci\u00f3n, Mapeo y Gesti\u00f3n de Flujos de Valor","Identification, Mapping &amp; Management of Value Streams"],["ITIL e IA","ITIL and AI"],["ITIL y Otros Marcos de Trabajo","ITIL and Other Frameworks"]];
const DTOPICS=[["Co-creaci\u00f3n de valor, utility, warranty, experience, sustainability, roles, interacciones","Value co-creation, utility, warranty, experience, sustainability, roles, interactions"],["O&amp;P, I&amp;T, S&amp;P, FV&amp;P, PESTLE, AI 6C Model, partner vs supplier","O&amp;P, I&amp;T, S&amp;P, FV&amp;P, PESTLE, AI 6C Model, partner vs supplier"],["8 actividades del lifecycle, feedback loops, stepping stones, Agile, retiro de servicios","8 lifecycle activities, feedback loops, stepping stones, Agile, service retirement"],["Principios gu\u00eda, gobernanza EDM, cadena de valor, 34 pr\u00e1cticas, mejora continua","Guiding principles, EDM governance, value chain, 34 practices, continual improvement"],["Value streams, customer journey, touchpoints, demand triggers, mapeo, optimizaci\u00f3n","Value streams, customer journey, touchpoints, demand triggers, mapping, optimization"],["AI 6C Model, \u00e9tica de IA, automatizaci\u00f3n, gobernanza digital, EDM, riesgos de IA","AI 6C Model, AI ethics, automation, digital governance, EDM, AI risks"],["DevOps, PRINCE2, Agile, Lean, COBIT, ISO 20000, SIAM, TOGAF, SAFe, SRE","DevOps, PRINCE2, Agile, Lean, COBIT, ISO 20000, SIAM, TOGAF, SAFe, SRE"]];
let DCOUNTS=[0,0,0,0,0,0,0];
let DSIM=[0,0,0,0,0,0,0];
const DWEIGHT=[30,10,10,40,5,2.5,2.5];
const UI={
title:["\uD83C\uDF93 ITIL v5 Foundation \u2014 Practice Exam Dashboard","\uD83C\uDF93 ITIL v5 Foundation \u2014 Practice Exam Dashboard"],
qs:["Preguntas","Questions"],
home:["\uD83C\uDFE0 Inicio","\uD83C\uDFE0 Home"],
hist:["\uD83D\uDCCA Historial","\uD83D\uDCCA History"],
info:["\u2139\uFE0F Info","\u2139\uFE0F Info"],
togLang:["\uD83C\uDF10 EN","\uD83C\uDF10 ES"],
themeTo:[["\u2600\uFE0F Claro","\u2600\uFE0F Light"],["\uD83C\uDF19 Oscuro","\uD83C\uDF19 Dark"]],
simBtn:["\uD83C\uDFAF Examen Simulado","\uD83C\uDFAF Mock Exam"],
fullBtn:["\uD83D\uDCD6 Pr\u00e1ctica Completa","\uD83D\uDCD6 Full Practice"],
domBtn:["\uD83D\uDCDA Dominios de Estudio","\uD83D\uDCDA Study Domains"],
smartBtn:["\uD83E\uDDE0 Repaso Inteligente","\uD83E\uDDE0 Smart Review"],
flashBtn:["\uD83D\uDCC7 Flashcards","\uD83D\uDCC7 Flashcards"],
adaptBtn:["\uD83C\uDFAF Adaptativo","\uD83C\uDFAF Adaptive"],
prev:["\u2B05 Anterior","\u2B05 Previous"],
next:["Siguiente \u27A1","Next \u27A1"],
flag:["\uD83D\uDEA9 Marcar","\uD83D\uDEA9 Flag"],
finish:["\u2705 Finalizar","\u2705 Finish"],
backHome:["\uD83C\uDFE0 Volver","\uD83C\uDFE0 Back Home"],
backDom:["\u2B05 Volver al Inicio","\u2B05 Back to Home"],
backExamDom:["\u2B05 Volver a Dominios","\u2B05 Back to Domains"],
backExamSim:["\u2B05 Volver al Simulado","\u2B05 Back to Mock Exam"],
backExamFull:["\u2B05 Volver al Inicio","\u2B05 Back to Home"],
backExamSmart:["\u2B05 Volver al Inicio","\u2B05 Back to Home"],
backExamAdapt:["\u2B05 Volver al Inicio","\u2B05 Back to Home"],
review:["\uD83D\uDD0D Revisar","\uD83D\uDD0D Review"],
clearHist:["\uD83D\uDDD1 Limpiar","\uD83D\uDDD1 Clear"],
histTitle:["\uD83D\uDCCA Historial","\uD83D\uDCCA History"],
pass:["\u2705 \u00a1APROBADO!","\u2705 PASSED!"],
fail:["\u274C NO APROBADO","\u274C NOT PASSED"],
of:["de","of"],
correct:["correctas","correct"],
approval:["Aprobaci\u00f3n","Pass mark"],
breakdown:["\uD83D\uDCCA Desglose por Dominio","\uD83D\uDCCA Domain Breakdown"],
strengths:["\uD83D\uDCAA Fortalezas","\uD83D\uDCAA Strengths"],
improve:["\uD83D\uDCDA Mejorar","\uD83D\uDCDA Improve"],
reviewTitle:["\uD83D\uDD0D Revisi\u00f3n","\uD83D\uDD0D Review"],
noAnswer:["\u26A0 Sin responder","\u26A0 Unanswered"],
yourAns:["Tu respuesta","Your answer"],
correctAns:["Correcta","Correct"],
noHist:["No hay intentos.","No attempts yet."],
date:["Fecha","Date"],
mode:["Modo","Mode"],
questions:["Preguntas","Questions"],
score:["Score","Score"],
status:["Estado","Status"],
trend:["\uD83D\uDCC8 Tendencia","\uD83D\uDCC8 Trend"],
simMode:["Simulado","Mock"],
fullMode:["Completo","Full"],
domMode:["Dominio","Domain"],
smartMode:["Repaso","Review"],
adaptMode:["Adaptativo","Adaptive"],
realLabel:["Real","Real"],
unanswered:["sin responder. \u00bfFinalizar?","unanswered. Finish?"],
tienes:["Tienes","You have"],
min:["min","min"],
deleteAll:["\u00bfEliminar historial?","Delete history?"],
summaryTitle:["\uD83D\uDCCA Resumen General","\uD83D\uDCCA General Summary"],
totalQs:["Total Preguntas","Total Questions"],
doms:["Dominios","Domains"],
examsDone:["Ex\u00e1menes Realizados","Exams Taken"],
bestScore:["Mejor Score","Best Score"],
domTitle:["\uD83D\uDCDA Dominios de Estudio","\uD83D\uDCDA Study Domains"],
domLabel:["Dominio","Domain"],
slTitle:["\uD83C\uDFAF Examen Simulado","\uD83C\uDFAF Mock Exam"],
slDesc:["40 preguntas aleatorias proporcionales al peso de cada dominio \u00b7 60 minutos \u00b7 65% para aprobar (26/40)","40 random questions proportional to each domain's weight \u00b7 60 minutes \u00b7 65% to pass (26/40)"],
slCD:["Dominio","Domain"],
slCW:["Peso","Weight"],
slCQ:["Preguntas","Questions"],
slStart:["\uD83D\uDE80 Comenzar Examen","\uD83D\uDE80 Start Exam"],
slBack:["\u2B05 Volver","\u2B05 Back"],
slTotal:["TOTAL","TOTAL"],
slRealLabel:["\uD83C\uDFC6 Modo PeopleCert Real (sin feedback hasta finalizar)","\uD83C\uDFC6 PeopleCert Real Mode (no feedback until finish)"],
qsLabel:["preguntas","questions"],
fullInfo:["Pr\u00e1ctica Completa","Full Practice"],
smartInfo:["Repaso Inteligente","Smart Review"],
adaptInfo:["Examen Adaptativo","Adaptive Exam"],
noWeak:["\u00a1No hay preguntas d\u00e9biles! Practica m\u00e1s.","No weak questions! Practice more."],
answered:["respondidas","answered"],
flashTitle:["\uD83D\uDCC7 Modo Flashcard","\uD83D\uDCC7 Flashcard Mode"],
flashTap:["\uD83D\uDC46 Toca para ver respuesta","\uD83D\uDC46 Tap to reveal answer"],
flashBack:["\u2B05 Volver","\u2B05 Back"],
progressTitle:["\uD83D\uDCCA Progreso por Pregunta","\uD83D\uDCCA Question Progress"],
mastered:["Dominadas","Mastered"],
weakLabel:["D\u00e9biles","Weak"],
inProgress:["En progreso","In Progress"],
unseenLabel:["Sin intentar","Unseen"],
resetStats:["\uD83D\uDDD1 Reiniciar Stats","\uD83D\uDDD1 Reset Stats"],
resetConfirm:["\u00bfEliminar estad\u00edsticas de preguntas?","Delete question stats?"],
avgTime:["Promedio","Average"],
timeStats:["\u23F1 Tiempo","\u23F1 Time"],
secQ:["seg/preg","sec/q"],
domPerf:["\uD83D\uDCCA Rendimiento por Dominio (acumulado)","\uD83D\uDCCA Domain Performance (cumulative)"],
planTitle:["\uD83C\uDFAF Plan Sugerido","\uD83C\uDFAF Suggested Plan"],
planStudy:["Estudia","Study"],
planReinforce:["Refuerza","Reinforce"],
planSmart:["\uD83E\uDDE0 Limpia errores con Repaso Inteligente","\uD83E\uDDE0 Clean up errors with Smart Review"],
planAdaptive:["\uD83C\uDFAF Valida mejora con Examen Adaptativo","\uD83C\uDFAF Validate improvement with Adaptive Exam"],
planMock:["\uD83C\uDFC6 Examen Simulado en modo PeopleCert Real","\uD83C\uDFC6 Mock Exam in PeopleCert Real mode"],
planReady:["\uD83C\uDFC6 \u00a1Est\u00e1s listo! Haz un simulado PeopleCert Real para confirmar.","\uD83C\uDFC6 You're ready! Take a PeopleCert Real mock to confirm."],
planNoPractice:["Practica para ver tu plan personalizado.","Practice to see your personalized plan."],
noStrWk:["Practica para ver tus fortalezas y debilidades.","Practice to see your strengths and weaknesses."],
infoSub:["Practice Exam Dashboard v"+APP_VERSION,"Practice Exam Dashboard v"+APP_VERSION],
infoFeatTitle:["\uD83D\uDEE0 Features","\uD83D\uDEE0 Features"],
infoKeyTitle:["\u2328\uFE0F Atajos de Teclado","\u2328\uFE0F Keyboard Shortcuts"],
infoKC1:["Tecla","Key"],
infoKC2:["Acci\u00f3n","Action"],
infoDisclaimer:["\uD83E\uDD16 100% generado por IA. No afiliado a PeopleCert, Axelos ni ning\u00fan organismo oficial. El contenido puede tener imprecisiones \u2014 \u00fasalo como complemento de estudio y siempre verifica con el material oficial. \u00a1T\u00fa pones el esfuerzo, la IA pone la pr\u00e1ctica! \uD83D\uDCAA","\uD83E\uDD16 100% AI-generated. Not affiliated with PeopleCert, Axelos or any official body. Content may contain inaccuracies \u2014 use it as a study complement and always verify with official material. You bring the effort, AI brings the practice! \uD83D\uDCAA"],
infoFooter:["ITIL v5 Foundation \u2014 Practice Exam Dashboard v"+APP_VERSION+" \u2014 100% generado por IA. No afiliado a PeopleCert, Axelos ni ning\u00fan organismo oficial.\nEl contenido puede tener imprecisiones \u2014 \u00fasalo como complemento de estudio y siempre verifica con el material oficial.\n\u00a1T\u00fa pones el esfuerzo, la IA pone la pr\u00e1ctica! \uD83D\uDCAA","ITIL v5 Foundation \u2014 Practice Exam Dashboard v"+APP_VERSION+" \u2014 100% AI-generated. Not affiliated with PeopleCert, Axelos or any official body.\nContent may contain inaccuracies \u2014 use it as a study complement and always verify with official material.\nYou bring the effort, AI brings the practice! \uD83D\uDCAA"],
exitConfirm:["\u00bfSalir del examen? Se perder\u00e1 el progreso.","Exit exam? Progress will be lost."]
};
const FEATS=[
[["\uD83D\uDCDD 620 Preguntas","Biling\u00fces ES/EN \u00b7 Conceptuales, escenarios reales y tipo negativa"],["\uD83D\uDCDD 620 Questions","Bilingual ES/EN \u00b7 Conceptual, real-world scenarios and negative type"]],
[["\uD83C\uDFAF Simulado","40 Qs proporcionales + timer 60 min + modo PeopleCert"],["\uD83C\uDFAF Mock","40 proportional Qs + 60 min timer + PeopleCert mode"]],
[["\uD83D\uDCDA 7 Dominios","Con contexto, temas clave y % de peso"],["\uD83D\uDCDA 7 Domains","With context, key topics and weight %"]],
[["\uD83D\uDCD6 Pr\u00e1ctica Completa","620 Qs con feedback inmediato por dominio o completa"],["\uD83D\uDCD6 Full Practice","620 Qs with immediate feedback by domain or full"]],
[["\uD83E\uDDE0 Repaso Inteligente","Practica solo las preguntas que has fallado"],["\uD83E\uDDE0 Smart Review","Practice only questions you've failed"]],
[["\uD83C\uDFAF Examen Adaptativo","M\u00e1s preguntas de tus dominios m\u00e1s d\u00e9biles"],["\uD83C\uDFAF Adaptive Exam","More questions from your weakest domains"]],
[["\uD83D\uDCC7 Flashcards","Modo estudio: pregunta \u2192 respuesta sin puntaje"],["\uD83D\uDCC7 Flashcards","Study mode: question \u2192 answer without scoring"]],
[["\uD83D\uDD0D Revisi\u00f3n","Cada pregunta con respuesta + explicaci\u00f3n"],["\uD83D\uDD0D Review","Each question with answer + explanation"]],
[["\uD83D\uDCCA Resultados","Score %, desglose, fortalezas/debilidades + acumulado"],["\uD83D\uDCCA Results","Score %, breakdown, strengths/weaknesses + cumulative"]],
[["\uD83C\uDFAF Plan Sugerido","Recomendaciones personalizadas seg\u00fan tu rendimiento"],["\uD83C\uDFAF Suggested Plan","Personalized recommendations based on your performance"]],
[["\uD83D\uDCCA Progreso","Tracking por pregunta: dominadas, d\u00e9biles, sin intentar"],["\uD83D\uDCCA Progress","Per-question tracking: mastered, weak, unseen"]],
[["\uD83D\uDCC8 Historial","Tendencia + rendimiento acumulado por dominio"],["\uD83D\uDCC8 History","Trend + cumulative domain performance"]],
[["\uD83D\uDD00 Aleatorizaci\u00f3n","Opciones A/B/C/D reordenadas en cada intento"],["\uD83D\uDD00 Randomization","A/B/C/D options reshuffled on every attempt"]],
[["\uD83D\uDEA9 Marcar Preguntas","Marca y revisa dudosas antes de finalizar"],["\uD83D\uDEA9 Flag Questions","Flag and review doubtful ones before finishing"]],
[["\u23F1 Tiempo por Pregunta","Estad\u00edsticas de velocidad al finalizar examen"],["\u23F1 Time per Question","Speed stats after finishing exam"]],
[["\uD83D\uDD25 Rachas","Contador de respuestas correctas consecutivas"],["\uD83D\uDD25 Streaks","Consecutive correct answer counter"]],
[["\uD83C\uDF10 ES/EN","Cambia TODO en tiempo real"],["\uD83C\uDF10 ES/EN","Switches EVERYTHING real-time"]],
[["\uD83D\uDCBE Auto-guardado","Contin\u00faa tu examen si cierras el navegador"],["\uD83D\uDCBE Auto-save","Continue your exam if you close the browser"]],
[["\uD83D\uDCF1 PWA Offline","Instalable en m\u00f3vil y funciona sin internet"],["\uD83D\uDCF1 PWA Offline","Installable on mobile and works without internet"]],
[["\u2328\uFE0F Atajos","\u2190 \u2192 A-D 1-4 F \u00b7 visibles en pantalla"],["\u2328\uFE0F Shortcuts","\u2190 \u2192 A-D 1-4 F \u00b7 visible on screen"]],
[["\uD83C\uDF19\u2600\uFE0F Tema","Oscuro / Claro persistente"],["\uD83C\uDF19\u2600\uFE0F Theme","Dark / Light persistent"]]
];
const KEYS=[
[["\u2190 \u2192","Anterior / siguiente"],["\u2190 \u2192","Previous / next"]],
[["A B C D","Seleccionar respuesta"],["A B C D","Select answer"]],
[["1 2 3 4","Seleccionar (alt)"],["1 2 3 4","Select (alt)"]],
[["F","Marcar / desmarcar"],["F","Flag / unflag"]]
];