var L=1,T=0,realMode=false;
var DICONS=["📖","🔲","🔄","⚙️","🗺️","🤖","🔗"];
var DCOLORS=["#58a6ff","#f0883e","#238636","#bc8cff","#f778ba","#79c0ff","#ffa657"];
var DN=[["D1 Términos y Conceptos","D1 Key Terms & Concepts"],["D2 Las 4 Dimensiones","D2 The 4 Dimensions"],["D3 PSLM (Lifecycle)","D3 PSLM (Lifecycle)"],["D4 Sistema de Valor ITIL","D4 ITIL Value System"],["D5 Flujos de Valor","D5 Value Streams"],["D6 ITIL e IA","D6 ITIL & AI"],["D7 ITIL y Otros Marcos","D7 ITIL & Frameworks"]];
var DFULL=[["Términos y Definiciones Clave","Key Terms & Definitions"],["Las Cuatro Dimensiones","The Four Dimensions"],["Ciclo de Vida del Producto y Servicio (PSLM)","Product & Service Lifecycle (PSLM)"],["Sistema de Valor ITIL (SVS)","ITIL Value System (SVS)"],["Identificación, Mapeo y Gestión de Flujos de Valor","Identification, Mapping & Management of Value Streams"],["ITIL e IA","ITIL and AI"],["ITIL y Otros Marcos de Trabajo","ITIL and Other Frameworks"]];
var DTOPICS=[["Co-creación de valor, utility, warranty, experience, sustainability, roles, interacciones","Value co-creation, utility, warranty, experience, sustainability, roles, interactions"],["O&P, I&T, S&P, FV&P, PESTLE, AI 6C Model, partner vs supplier","O&P, I&T, S&P, FV&P, PESTLE, AI 6C Model, partner vs supplier"],["8 actividades del lifecycle, feedback loops, stepping stones, Agile, retiro de servicios","8 lifecycle activities, feedback loops, stepping stones, Agile, service retirement"],["Principios guía, gobernanza EDM, cadena de valor, 34 prácticas, mejora continua","Guiding principles, EDM governance, value chain, 34 practices, continual improvement"],["Value streams, customer journey, touchpoints, demand triggers, mapeo, optimización","Value streams, customer journey, touchpoints, demand triggers, mapping, optimization"],["AI 6C Model, ética de IA, automatización, gobernanza digital, EDM, riesgos de IA","AI 6C Model, AI ethics, automation, digital governance, EDM, AI risks"],["DevOps, PRINCE2, Agile, Lean, COBIT, ISO 20000, SIAM, TOGAF, SAFe, SRE","DevOps, PRINCE2, Agile, Lean, COBIT, ISO 20000, SIAM, TOGAF, SAFe, SRE"]];
var DCOUNTS=[0,0,0,0,0,0,0];
var DSIM=[0,0,0,0,0,0,0];
var DWEIGHT=[30,10,10,40,5,2.5,2.5];
var UI={
title:["🎓 ITIL v5 Foundation — Practice Exam Dashboard","🎓 ITIL v5 Foundation — Practice Exam Dashboard"],
qs:["Preguntas","Questions"],
home:["🏠 Inicio","🏠 Home"],
hist:["📊 Historial","📊 History"],
info:["ℹ️ Info","ℹ️ Info"],
togLang:["🌐 EN","🌐 ES"],
themeTo:[["☀️ Claro","☀️ Light"],["🌙 Oscuro","🌙 Dark"]],
simBtn:["🎯 Examen Simulado","🎯 Mock Exam"],
fullBtn:["📖 Práctica Completa","📖 Full Practice"],
domBtn:["📚 Dominios de Estudio","📚 Study Domains"],
smartBtn:["🧠 Repaso Inteligente","🧠 Smart Review"],
flashBtn:["📇 Flashcards","📇 Flashcards"],
adaptBtn:["🎯 Adaptativo","🎯 Adaptive"],
prev:["⬅ Anterior","⬅ Previous"],
next:["Siguiente ➡","Next ➡"],
flag:["🚩 Marcar","🚩 Flag"],
finish:["✅ Finalizar","✅ Finish"],
backHome:["🏠 Volver","🏠 Back Home"],
backDom:["⬅ Volver al Inicio","⬅ Back to Home"],
backExamDom:["⬅ Volver a Dominios","⬅ Back to Domains"],
backExamSim:["⬅ Volver al Simulado","⬅ Back to Mock Exam"],
backExamFull:["⬅ Volver al Inicio","⬅ Back to Home"],
backExamSmart:["⬅ Volver al Inicio","⬅ Back to Home"],
backExamAdapt:["⬅ Volver al Inicio","⬅ Back to Home"],
review:["🔍 Revisar","🔍 Review"],
clearHist:["🗑 Limpiar","🗑 Clear"],
histTitle:["📊 Historial","📊 History"],
pass:["✅ ¡APROBADO!","✅ PASSED!"],
fail:["❌ NO APROBADO","❌ NOT PASSED"],
of:["de","of"],
correct:["correctas","correct"],
approval:["Aprobación","Pass mark"],
breakdown:["📊 Desglose por Dominio","📊 Domain Breakdown"],
strengths:["💪 Fortalezas","💪 Strengths"],
improve:["📚 Mejorar","📚 Improve"],
reviewTitle:["🔍 Revisión","🔍 Review"],
noAnswer:["⚠ Sin responder","⚠ Unanswered"],
yourAns:["Tu respuesta","Your answer"],
correctAns:["Correcta","Correct"],
noHist:["No hay intentos.","No attempts yet."],
date:["Fecha","Date"],
mode:["Modo","Mode"],
questions:["Preguntas","Questions"],
score:["Score","Score"],
status:["Estado","Status"],
trend:["📈 Tendencia","📈 Trend"],
simMode:["Simulado","Mock"],
fullMode:["Completo","Full"],
domMode:["Dominio","Domain"],
smartMode:["Repaso","Review"],
adaptMode:["Adaptativo","Adaptive"],
realLabel:["Real","Real"],
unanswered:["sin responder. ¿Finalizar?","unanswered. Finish?"],
tienes:["Tienes","You have"],
min:["min","min"],
deleteAll:["¿Eliminar historial?","Delete history?"],
summaryTitle:["📊 Resumen General","📊 General Summary"],
totalQs:["Total Preguntas","Total Questions"],
doms:["Dominios","Domains"],
examsDone:["Exámenes Realizados","Exams Taken"],
bestScore:["Mejor Score","Best Score"],
domTitle:["📚 Dominios de Estudio","📚 Study Domains"],
domLabel:["Dominio","Domain"],
slTitle:["🎯 Examen Simulado","🎯 Mock Exam"],
slDesc:["40 preguntas aleatorias proporcionales al peso de cada dominio · 60 minutos · 65% para aprobar (26/40)","40 random questions proportional to each domain's weight · 60 minutes · 65% to pass (26/40)"],
slCD:["Dominio","Domain"],
slCW:["Peso","Weight"],
slCQ:["Preguntas","Questions"],
slStart:["🚀 Comenzar Examen","🚀 Start Exam"],
slBack:["⬅ Volver","⬅ Back"],
slTotal:["TOTAL","TOTAL"],
slRealLabel:["🏆 Modo PeopleCert Real (sin feedback hasta finalizar)","🏆 PeopleCert Real Mode (no feedback until finish)"],
qsLabel:["preguntas","questions"],
fullInfo:["Práctica Completa","Full Practice"],
smartInfo:["Repaso Inteligente","Smart Review"],
adaptInfo:["Examen Adaptativo","Adaptive Exam"],
noWeak:["¡No hay preguntas débiles! Practica más.","No weak questions! Practice more."],
answered:["respondidas","answered"],
flashTitle:["📇 Modo Flashcard","📇 Flashcard Mode"],
flashTap:["👆 Toca para ver respuesta","👆 Tap to reveal answer"],
flashBack:["⬅ Volver","⬅ Back"],
progressTitle:["📊 Progreso por Pregunta","📊 Question Progress"],
mastered:["Dominadas","Mastered"],
weakLabel:["Débiles","Weak"],
inProgress:["En progreso","In Progress"],
unseenLabel:["Sin intentar","Unseen"],
resetStats:["🗑 Reiniciar Stats","🗑 Reset Stats"],
resetConfirm:["¿Eliminar estadísticas de preguntas?","Delete question stats?"],
avgTime:["Promedio","Average"],
timeStats:["⏱ Tiempo","⏱ Time"],
secQ:["seg/preg","sec/q"],
domPerf:["📊 Rendimiento por Dominio (acumulado)","📊 Domain Performance (cumulative)"],
planTitle:["🎯 Plan Sugerido","🎯 Suggested Plan"],
planStudy:["Estudia","Study"],
planReinforce:["Refuerza","Reinforce"],
planSmart:["🧠 Limpia errores con Repaso Inteligente","🧠 Clean up errors with Smart Review"],
planAdaptive:["🎯 Valida mejora con Examen Adaptativo","🎯 Validate improvement with Adaptive Exam"],
planMock:["🏆 Examen Simulado en modo PeopleCert Real","🏆 Mock Exam in PeopleCert Real mode"],
planReady:["🏆 ¡Estás listo! Haz un simulado PeopleCert Real para confirmar.","🏆 You're ready! Take a PeopleCert Real mock to confirm."],
planNoPractice:["Practica para ver tu plan personalizado.","Practice to see your personalized plan."],
noStrWk:["Practica para ver tus fortalezas y debilidades.","Practice to see your strengths and weaknesses."],
infoSub:["Practice Exam Dashboard v5.0","Practice Exam Dashboard v5.0"],
infoFeatTitle:["🛠 Features","🛠 Features"],
infoKeyTitle:["⌨️ Atajos de Teclado","⌨️ Keyboard Shortcuts"],
infoKC1:["Tecla","Key"],
infoKC2:["Acción","Action"],
infoDisclaimer:["🤖 100% generado por IA. No afiliado a PeopleCert, Axelos ni ningún organismo oficial. El contenido puede tener imprecisiones — úsalo como complemento de estudio y siempre verifica con el material oficial. ¡Tú pones el esfuerzo, la IA pone la práctica! 💪","🤖 100% AI-generated. Not affiliated with PeopleCert, Axelos or any official body. Content may contain inaccuracies — use it as a study complement and always verify with official material. You bring the effort, AI brings the practice! 💪"],
infoFooter:["Syllabus PeopleCert v5.0 (Feb 2026)\nDashboard v5.0 — 620 Preguntas — Mayo 2026\n🤖 100% generado por IA. No afiliado a PeopleCert, Axelos ni ningún organismo oficial.\nEl contenido puede tener imprecisiones — úsalo como complemento de estudio y siempre verifica con el material oficial.\n¡Tú pones el esfuerzo, la IA pone la práctica! 💪","PeopleCert v5.0 Syllabus (Feb 2026)\nDashboard v5.0 — 620 Questions — May 2026\n🤖 100% AI-generated. Not affiliated with PeopleCert, Axelos or any official body.\nContent may contain inaccuracies — use it as a study complement and always verify with official material.\nYou bring the effort, AI brings the practice! 💪"],
exitConfirm:["¿Salir del examen? Se perderá el progreso.","Exit exam? Progress will be lost."]
};
var FEATS=[
[["📝 620 Preguntas","Bilingües ES/EN · Conceptuales, escenarios reales y tipo negativa"],["📝 620 Questions","Bilingual ES/EN · Conceptual, real-world scenarios and negative type"]],
[["🎯 Simulado","40 Qs proporcionales + timer 60 min + modo PeopleCert"],["🎯 Mock","40 proportional Qs + 60 min timer + PeopleCert mode"]],
[["📚 7 Dominios","Con contexto, temas clave y % de peso"],["📚 7 Domains","With context, key topics and weight %"]],
[["📖 Práctica Completa","620 Qs con feedback inmediato por dominio o completa"],["📖 Full Practice","620 Qs with immediate feedback by domain or full"]],
[["🧠 Repaso Inteligente","Practica solo las preguntas que has fallado"],["🧠 Smart Review","Practice only questions you've failed"]],
[["🎯 Examen Adaptativo","Más preguntas de tus dominios más débiles"],["🎯 Adaptive Exam","More questions from your weakest domains"]],
[["📇 Flashcards","Modo estudio: pregunta → respuesta sin puntaje"],["📇 Flashcards","Study mode: question → answer without scoring"]],
[["🔍 Revisión","Cada pregunta con respuesta + explicación"],["🔍 Review","Each question with answer + explanation"]],
[["📊 Resultados","Score %, desglose, fortalezas/debilidades + acumulado"],["📊 Results","Score %, breakdown, strengths/weaknesses + cumulative"]],
[["🎯 Plan Sugerido","Recomendaciones personalizadas según tu rendimiento"],["🎯 Suggested Plan","Personalized recommendations based on your performance"]],
[["📊 Progreso","Tracking por pregunta: dominadas, débiles, sin intentar"],["📊 Progress","Per-question tracking: mastered, weak, unseen"]],
[["📈 Historial","Tendencia + rendimiento acumulado por dominio"],["📈 History","Trend + cumulative domain performance"]],
[["🔀 Aleatorización","Opciones A/B/C/D reordenadas en cada intento"],["🔀 Randomization","A/B/C/D options reshuffled on every attempt"]],
[["🚩 Marcar Preguntas","Marca y revisa dudosas antes de finalizar"],["🚩 Flag Questions","Flag and review doubtful ones before finishing"]],
[["⏱ Tiempo por Pregunta","Estadísticas de velocidad al finalizar examen"],["⏱ Time per Question","Speed stats after finishing exam"]],
[["🔥 Rachas","Contador de respuestas correctas consecutivas"],["🔥 Streaks","Consecutive correct answer counter"]],
[["🌐 ES/EN","Cambia TODO en tiempo real"],["🌐 ES/EN","Switches EVERYTHING real-time"]],
[["💾 Auto-guardado","Continúa tu examen si cierras el navegador"],["💾 Auto-save","Continue your exam if you close the browser"]],
[["📱 PWA Offline","Instalable en móvil y funciona sin internet"],["📱 PWA Offline","Installable on mobile and works without internet"]],
[["⌨️ Atajos","← → A-D 1-4 F · visibles en pantalla"],["⌨️ Shortcuts","← → A-D 1-4 F · visible on screen"]],
[["🌙☀️ Tema","Oscuro / Claro persistente"],["🌙☀️ Theme","Dark / Light persistent"]]
];
var KEYS=[
[["← →","Anterior / siguiente"],["← →","Previous / next"]],
[["A B C D","Seleccionar respuesta"],["A B C D","Select answer"]],
[["1 2 3 4","Seleccionar (alt)"],["1 2 3 4","Select (alt)"]],
[["F","Marcar / desmarcar"],["F","Flag / unflag"]]
];